[package]
name = "simple-nft"
version = "0.1.0"

[addresses]
StarcoinFramework = "0x1"
SNFT = "0x6855ee1e49777457cc1b02c718074135"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="main"}
#StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="2b726cc43dd65a25ad46ba55a8b9149528b2c18d"}
